name: Hello GitHub Actions

on:
  push:
    branches:
      - main  # mainブランチにpushされたら実行

jobs:
  hello_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run a simple command
        run: echo "Hello GitHub Actions!"
